modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="random_shit"
version="1.0.0"
displayName="random shit"
credits="Made by Boof V2#4806"
displayURL="https://mcreator.net"
authors="Boof"

[[dependencies.random_shit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




